# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WB8Dp5PWF-kZQStGExLWAoQrMK5fX6c9
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load trained model
@st.cache_resource
def load_model():
    with open("model.pkl", "rb") as file:
        model = pickle.load(file)
    return model

model = load_model()

# UI
st.title("🩺 Diabetes Risk Prediction App (using .pkl model)")

st.sidebar.header("Enter Patient Details")

blood_glucose = st.sidebar.number_input("Blood Glucose", min_value=0, max_value=500, step=1)
bmi = st.sidebar.number_input("BMI", min_value=0.0, max_value=100.0, step=0.1)
age = st.sidebar.number_input("Age", min_value=0, max_value=120, step=1)
weight = st.sidebar.number_input("Weight (kg)", min_value=0, max_value=300, step=1)

if st.sidebar.button("Predict"):
    input_data = [[blood_glucose, bmi, age, weight]]
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("⚠️ High Risk of Diabetes")
    else:
        st.success("✅ Low Risk of Diabetes")