# -*- coding: utf-8 -*-
"""appp_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WB8Dp5PWF-kZQStGExLWAoQrMK5fX6c9
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained model
model = pickle.load(open("model (5).pkl", "rb"))

# Streamlit UI
st.title("Diabetes Risk Prediction")

st.markdown("Enter the patient data below to predict the **risk score**:")

# Input fields
blood_glucose = st.number_input("Blood Glucose", min_value=0.0, step=0.1)
bmi = st.number_input("BMI", min_value=0.0, step=0.1)
height = st.number_input("Height (cm)", min_value=0.0, step=0.1)
weight = st.number_input("Weight (kg)", min_value=0.0, step=0.1)

# Predict button
if st.button("Predict"):
    # Prepare input in the order the model was trained on
    input_data = np.array([[blood_glucose, bmi, height, weight]])

    # Predict using the model
    prediction = model.predict(input_data)

    #